- DecisionTreeClassifier로 예측한 성능이 가장 좋은 데이터셋을 선택
- RandomForestClassifer
- XGBosst

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data1=pd.read_csv('data1.csv')

In [3]:
data1.head()

Survived  Pclass                                               Name  \
0         0       3                            Braund, Mr. Owen Harris   
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2         1       3                             Heikkinen, Miss. Laina   
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4         0       3                           Allen, Mr. William Henry   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S  
1  female  38.0      1      0          PC 17599  71.2833   C85        C  
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3  female  35.0      1      0            113803  53.1000  C123        S  
4    male  35.0      0      0            373450   8.0500   NaN        S

In [4]:
data1.isnull().sum()

Survived      0
Pclass        0
Name          0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [5]:
data2=pd.read_csv('data2.csv')

In [6]:
data2.head()

age2 Embarked     Fare  SibSp  Parch  Pclass     Sex  Survived
0  22.0        S   7.2500      1      0       3    male         0
1  38.0        C  71.2833      1      0       1  female         1
2  26.0        S   7.9250      0      0       3  female         1
3  35.0        S  53.1000      1      0       1  female         1
4  35.0        S   8.0500      0      0       3    male         0

In [7]:
data2.isnull().sum()

age2        0
Embarked    0
Fare        0
SibSp       0
Parch       0
Pclass      0
Sex         0
Survived    0
dtype: int64

In [8]:
data3=pd.read_csv('data3.csv')

In [9]:
data3.head()

age_range Embarked     Fare  SibSp  Parch  Pclass     Sex  Survived
0          1        S   7.2500      1      0       3    male         0
1          1        C  71.2833      1      0       1  female         1
2          1        S   7.9250      0      0       3  female         1
3          1        S  53.1000      1      0       1  female         1
4          1        S   8.0500      0      0       3    male         0

In [10]:
data3.isnull().sum()

age_range    0
Embarked     0
Fare         0
SibSp        0
Parch        0
Pclass       0
Sex          0
Survived     0
dtype: int64

In [11]:
data4=pd.read_csv('data4.csv')

In [12]:
data4.head()

age_range Embarked     Fare  family_size title  Pclass     Sex  Survived
0          1        S   7.2500            2    mr       3    male         0
1          1        C  71.2833            2   mrs       1  female         1
2          1        S   7.9250            1  miss       3  female         1
3          1        S  53.1000            2   mrs       1  female         1
4          1        S   8.0500            1    mr       3    male         0

In [13]:
data4['Embarked'].fillna(data4['Embarked'].mode().values[0],inplace=True)

In [14]:
data4.isnull().sum()

age_range      0
Embarked       0
Fare           0
family_size    0
title          0
Pclass         0
Sex            0
Survived       0
dtype: int64

In [15]:
# data1: 전처리 하지 않고 그대로 사용
# data2~4 : 필요한 전처리 적용 후 사용

In [16]:
# 의사결정나무 모델에서의 일반화 성능이 제일 높은 데이터셋 고르기
from sklearn.tree import DecisionTreeRegressor

In [17]:
dtree=DecisionTreeRegressor()

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
# data2,3,4 : Embarked 변수를 OneHotEncoding
# data4 : title 변수를 숫자로 바꿔준다.

In [20]:
# data1
# Name ,Ticket 삭제
# Sex,Cabin, Embarked : LabelEncoder
data1.drop(['Name','Ticket'],axis=1,inplace=True)

In [21]:
# 1. 모델링에 필요한 전처리 수행
# 2. 모델링에 필요한 데이터 분리 수행
# 3. 모델 학습
# 4. 모델 평가
# 5. 최종결과는 딕셔너리 형태로 저장

In [22]:
# OneHotEncoding

# embarked,Pclass,Sex

# age_range , Embarked,Pclass,Sex

# age_range, Embarked,Family_size,Pclass,sex

In [23]:
from sklearn import preprocessing

In [24]:
ohe=preprocessing.OneHotEncoder()
label_encoder=preprocessing.LabelEncoder()

In [25]:
data1['Sex']=label_encoder.fit_transform(data1['Sex'])

In [26]:
data1.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    1  22.0      1      0   7.2500   NaN        S
1         1       1    0  38.0      1      0  71.2833   C85        C
2         1       3    0  26.0      0      0   7.9250   NaN        S
3         1       1    0  35.0      1      0  53.1000  C123        S
4         0       3    1  35.0      0      0   8.0500   NaN        S

In [27]:
data1['Cabin'].fillna('none',inplace=True)

In [28]:
data1['Embarked'].fillna('none',inplace=True)

In [29]:
# 결측치 제거 / 대체를 해줘야 encoder 적용이 가능함
data1['Cabin']=label_encoder.fit_transform(data1['Cabin'])
data1['Embarked']=label_encoder.fit_transform(data1['Embarked'])

In [30]:
data1.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Cabin  Embarked
0         0       3    1  22.0      1      0   7.2500    147         2
1         1       1    0  38.0      1      0  71.2833     81         0
2         1       3    0  26.0      0      0   7.9250    147         2
3         1       1    0  35.0      1      0  53.1000     55         2
4         0       3    1  35.0      0      0   8.0500    147         2

In [31]:
x=ohe.fit_transform(data2['Embarked'].values.reshape(-1,1)).toarray()

In [32]:
ohe_embarked=pd.DataFrame(x,columns=['e1','e2','e3'])
ohe_embarked.head()

e1   e2   e3
0  0.0  0.0  1.0
1  1.0  0.0  0.0
2  0.0  0.0  1.0
3  0.0  0.0  1.0
4  0.0  0.0  1.0

In [33]:
y=ohe.fit_transform(data2['Pclass'].values.reshape(-1,1)).toarray()
ohe_pclass=pd.DataFrame(y,columns=['p1','p2','p3'])
ohe_pclass.head()

p1   p2   p3
0  0.0  0.0  1.0
1  1.0  0.0  0.0
2  0.0  0.0  1.0
3  1.0  0.0  0.0
4  0.0  0.0  1.0

In [34]:
z=ohe.fit_transform(data2['Sex'].values.reshape(-1,1)).toarray()
ohe_sex=pd.DataFrame(z,columns=['s1','s2'])
ohe_sex.head()

s1   s2
0  0.0  1.0
1  1.0  0.0
2  1.0  0.0
3  1.0  0.0
4  0.0  1.0

In [35]:
data2.drop(['Embarked','Pclass','Sex'],axis=1,inplace=True)


In [36]:
data2=pd.concat([data2,ohe_embarked,ohe_pclass,ohe_sex],axis=1)
data2

age2      Fare  SibSp  Parch  Survived   e1   e2   e3   p1   p2  \
0    22.000000    7.2500      1      0         0  0.0  0.0  1.0  0.0  0.0   
1    38.000000   71.2833      1      0         1  1.0  0.0  0.0  1.0  0.0   
2    26.000000    7.9250      0      0         1  0.0  0.0  1.0  0.0  0.0   
3    35.000000   53.1000      1      0         1  0.0  0.0  1.0  1.0  0.0   
4    35.000000    8.0500      0      0         0  0.0  0.0  1.0  0.0  0.0   
5    32.368090    8.4583      0      0         0  0.0  1.0  0.0  0.0  0.0   
6    54.000000   51.8625      0      0         0  0.0  0.0  1.0  1.0  0.0   
7     2.000000   21.0750      3      1         0  0.0  0.0  1.0  0.0  0.0   
8    27.000000   11.1333      0      2         1  0.0  0.0  1.0  0.0  0.0   
9    14.000000   30.0708      1      0         1  1.0  0.0  0.0  0.0  1.0   
10    4.000000   16.7000      1      1         1  0.0  0.0  1.0  0.0  0.0   
11   58.000000   26.5500      0      0         1  0.0  0.0  1.0  1.0  0.0   
12   20.000000    8.0500      0      0         0  0.0  0.0  1.0  0.0  0.0   
13   39.000000   31.2750      1      5         0  0.0  0.0  1.0  0.0  0.0   
14   14.000000    7.8542      0      0         0  0.0  0.0  1.0  0.0  0.0   
15   55.000000   16.0000      0      0         1  0.0  0.0  1.0  0.0  1.0   
16    2.000000   29.1250      4      1         0  0.0  1.0  0.0  0.0  0.0   
17   32.368090   13.0000      0      0         1  0.0  0.0  1.0  0.0  1.0   
18   31.000000   18.0000      1      0         0  0.0  0.0  1.0  0.0  0.0   
19   35.898148    7.2250      0      0         1  1.0  0.0  0.0  0.0  0.0   
20   35.000000   26.0000      0      0         0  0.0  0.0  1.0  0.0  1.0   
21   34.000000   13.0000      0      0         1  0.0  0.0  1.0  0.0  1.0   
22   15.000000    8.0292      0      0         1  0.0  1.0  0.0  0.0  0.0   
23   28.000000   35.5000      0      0         1  0.0  0.0  1.0  1.0  0.0   
24    8.000000   21.0750      3      1         0  0.0  0.0  1.0  0.0  0.0   
25   38.000000   31.3875      1      5         1  0.0  0.0  1.0  0.0  0.0   
26   32.368090    7.2250      0      0         0  1.0  0.0  0.0  0.0  0.0   
27   19.000000  263.0000      3      2         0  0.0  0.0  1.0  1.0  0.0   
28   21.773973    7.8792      0      0         1  0.0  1.0  0.0  0.0  0.0   
29   32.368090    7.8958      0      0         0  0.0  0.0  1.0  0.0  0.0   
..         ...       ...    ...    ...       ...  ...  ...  ...  ...  ...   
861  21.000000   11.5000      1      0         0  0.0  0.0  1.0  0.0  1.0   
862  48.000000   25.9292      0      0         1  0.0  0.0  1.0  1.0  0.0   
863  21.773973   69.5500      8      2         0  0.0  0.0  1.0  0.0  0.0   
864  24.000000   13.0000      0      0         0  0.0  0.0  1.0  0.0  1.0   
865  42.000000   13.0000      0      0         1  0.0  0.0  1.0  0.0  1.0   
866  27.000000   13.8583      1      0         1  1.0  0.0  0.0  0.0  1.0   
867  31.000000   50.4958      0      0         0  0.0  0.0  1.0  1.0  0.0   
868  32.368090    9.5000      0      0         0  0.0  0.0  1.0  0.0  0.0   
869   4.000000   11.1333      1      1         1  0.0  0.0  1.0  0.0  0.0   
870  26.000000    7.8958      0      0         0  0.0  0.0  1.0  0.0  0.0   
871  47.000000   52.5542      1      1         1  0.0  0.0  1.0  1.0  0.0   
872  33.000000    5.0000      0      0         0  0.0  0.0  1.0  1.0  0.0   
873  47.000000    9.0000      0      0         0  0.0  0.0  1.0  0.0  0.0   
874  28.000000   24.0000      1      0         1  1.0  0.0  0.0  0.0  1.0   
875  15.000000    7.2250      0      0         1  1.0  0.0  0.0  0.0  0.0   
876  20.000000    9.8458      0      0         0  0.0  0.0  1.0  0.0  0.0   
877  19.000000    7.8958      0      0         0  0.0  0.0  1.0  0.0  0.0   
878  32.368090    7.8958      0      0         0  0.0  0.0  1.0  0.0  0.0   
879  56.000000   83.1583      0      1         1  1.0  0.0  0.0  1.0  0.0   
880  25.000000   26.0000      0      1         1  0.0  0.0  1.0  0.0  1.0   
881  3

In [39]:
from sklearn.preprocessing import OneHotEncoder

In [40]:
# data3
# age_range , Embarked,Pclass,Sex
# 사용자 정의 함수
def ohe_trans(df,col):
    ohe=OneHotEncoder()
    x=ohe.fit_transform(df[col].values.reshape(-1,1)).toarray()
    tmp=[]
    for i in range(df[col].unique().size):
        tmp.append(col[0]+str(i))
        
    ohe_df=pd.DataFrame(x,columns=tmp)
    
    return ohe_df

In [41]:
ohe_trans(data3,'age_range')

C:\Users\winst\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


a0   a1   a2   a3
0    0.0  1.0  0.0  0.0
1    0.0  1.0  0.0  0.0
2    0.0  1.0  0.0  0.0
3    0.0  1.0  0.0  0.0
4    0.0  1.0  0.0  0.0
5    0.0  1.0  0.0  0.0
6    0.0  0.0  1.0  0.0
7    1.0  0.0  0.0  0.0
8    0.0  1.0  0.0  0.0
9    1.0  0.0  0.0  0.0
10   1.0  0.0  0.0  0.0
11   0.0  0.0  1.0  0.0
12   0.0  1.0  0.0  0.0
13   0.0  1.0  0.0  0.0
14   1.0  0.0  0.0  0.0
15   0.0  0.0  1.0  0.0
16   1.0  0.0  0.0  0.0
17   0.0  1.0  0.0  0.0
18   0.0  1.0  0.0  0.0
19   0.0  1.0  0.0  0.0
20   0.0  1.0  0.0  0.0
21   0.0  1.0  0.0  0.0
22   1.0  0.0  0.0  0.0
23   0.0  1.0  0.0  0.0
24   1.0  0.0  0.0  0.0
25   0.0  1.0  0.0  0.0
26   0.0  1.0  0.0  0.0
27   1.0  0.0  0.0  0.0
28   0.0  1.0  0.0  0.0
29   0.0  1.0  0.0  0.0
..   ...  ...  ...  ...
861  0.0  1.0  0.0  0.0
862  0.0  0.0  1.0  0.0
863  0.0  1.0  0.0  0.0
864  0.0  1.0  0.0  0.0
865  0.0  0.0  1.0  0.0
866  0.0  1.0  0.0  0.0
867  0.0  1.0  0.0  0.0
868  0.0  1.0  0.0  0.0
869  1.0  0.0  0.0  0.0
870  0.0  1.0  0.0  0.0
871  0.0  0.0  1.0  0.0
872  0.0  1.0  0.0  0.0
873  0.0  0.0  1.0  0.0
874  0.0  1.0  0.0  0.0
875  1.0  0.0  0.0  0.0
876  0.0  1.0  0.0  0.0
877  1.0  0.0  0.0  0.0
878  0.0  1.0  0.0  0.0
879  0.0  0.0  1.0  0.0
880  0.0  1.0  0.0  0.0
881  0.0  1.0  0.0  0.0
882  0.0  1.0  0.0  0.0
883  0.0  1.0  0.0  0.0
884  0.0  1.0  0.0  0.0
885  0.0  1.0  0.0  0.0
886  0.0  1.0  0.0  0.0
887  1.0  0.0  0.0  0.0
888  0.0  1.0  0.0  0.0
889  0.0  1.0  0.0  0.0
890  0.0  1.0  0.0  0.0

[891 rows x 4 columns]

In [42]:
result1=ohe_trans(data3,'age_range')
result2=ohe_trans(data3,'Embarked')
result3=ohe_trans(data3,'Pclass')
result4=ohe_trans(data3,'Sex')

C:\Users\winst\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\winst\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you us

In [43]:
data3.drop(['age_range','Embarked','Pclass','Sex'],axis=1,inplace=True)

In [44]:
data3=pd.concat([data3,result1,result2,result3,result4],axis=1)

In [45]:
data3.head()

Fare  SibSp  Parch  Survived   a0   a1   a2   a3   E0   E1   E2   P0  \
0   7.2500      1      0         0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   
1  71.2833      1      0         1  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0   
2   7.9250      0      0         1  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   
3  53.1000      1      0         1  0.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0   
4   8.0500      0      0         0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   

    P1   P2   S0   S1  
0  0.0  1.0  0.0  1.0  
1  0.0  0.0  1.0  0.0  
2  0.0  1.0  1.0  0.0  
3  0.0  0.0  1.0  0.0  
4  0.0  1.0  0.0  1.0

In [46]:
data4.columns

Index(['age_range', 'Embarked', 'Fare', 'family_size', 'title', 'Pclass',
       'Sex', 'Survived'],
      dtype='object')

In [47]:
r1=ohe_trans(data4,'age_range')
r2=ohe_trans(data4,'Embarked')
r3=ohe_trans(data4,'family_size')
r4=ohe_trans(data4,'Pclass')
r5=ohe_trans(data4,'Sex')

C:\Users\winst\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\winst\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you us

In [48]:
data4.isnull().sum()

age_range      0
Embarked       0
Fare           0
family_size    0
title          0
Pclass         0
Sex            0
Survived       0
dtype: int64

In [49]:
data4.drop(['age_range','Embarked','family_size','Pclass','Sex'],axis=1,inplace=True)

In [50]:
data4=pd.concat([data4,r1,r2,r3,r4,r5],axis=1)

In [51]:
data4.head()

Fare title  Survived   a0   a1   a2   a3   E0   E1   E2 ...    f4   f5  \
0   7.2500    mr         0  0.0  1.0  0.0  0.0  0.0  0.0  1.0 ...   0.0  0.0   
1  71.2833   mrs         1  0.0  1.0  0.0  0.0  1.0  0.0  0.0 ...   0.0  0.0   
2   7.9250  miss         1  0.0  1.0  0.0  0.0  0.0  0.0  1.0 ...   0.0  0.0   
3  53.1000   mrs         1  0.0  1.0  0.0  0.0  0.0  0.0  1.0 ...   0.0  0.0   
4   8.0500    mr         0  0.0  1.0  0.0  0.0  0.0  0.0  1.0 ...   0.0  0.0   

    f6   f7   f8   P0   P1   P2   S0   S1  
0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
1  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  
3  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  

[5 rows x 24 columns]

In [52]:
from sklearn.tree import DecisionTreeClassifier

In [53]:
dtree=DecisionTreeClassifier()

In [54]:
from sklearn.model_selection import train_test_split

In [55]:
data1_x=data1.drop(['Survived','Age'],axis=1)
data1_y=data1['Survived'].copy()

In [56]:
train_x1,test_x1,train_y1,test_y1=train_test_split(data1_x,data1_y,test_size=.2)

In [57]:
dtree.fit(train_x1,train_y1)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [58]:
dtree.predict(test_x1)

array([0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0], dtype=int64)

In [59]:
# data1 에 대한 score
data1_score=dtree.score(test_x1,test_y1)

In [60]:
data1_score

0.8379888268156425

In [61]:
data2_x=data2.drop('Survived',axis=1).copy()
data2_y=data2['Survived'].copy()

In [62]:
train_x2,test_x2,train_y2,test_y2=train_test_split(data2_x,data2_y,test_size=.2)

In [63]:
dtree.fit(train_x2,train_y2)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [64]:
dtree.predict(train_x2)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,

In [65]:
dtree.predict(test_x2)

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0], dtype=int64)

In [66]:
# data2에 대한 score
data2_score=dtree.score(test_x2,test_y2)

In [67]:
data3_x=data3.drop('Survived',axis=1).copy()
data3_y=data3['Survived'].copy()

In [68]:
train_x3,test_x3,train_y3,test_y3=train_test_split(data3_x,data3_y,test_size=.2)

In [69]:
dtree.fit(train_x3,train_y3)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [70]:
dtree.predict(test_x3)

array([0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0], dtype=int64)

In [71]:
# data3에 대한 score
data3_score=dtree.score(test_x3,test_y3)

In [72]:
data3_score

0.7821229050279329

In [73]:
data4_v1=data4.copy()

In [77]:
r=ohe_trans(data4_v1,'title')

In [79]:
data4.drop('title',axis=1,inplace=True)


KeyError: "['title'] not found in axis"

In [80]:
data4=pd.concat([data4,r],axis=1)

In [81]:
data4_x=data4.drop('Survived',axis=1).copy()
data4_y=data4['Survived'].copy()
train_x4,test_x4,train_y4,test_y4=train_test_split(data3_x,data3_y,test_size=.2)

In [82]:
dtree.fit(train_x4,train_y4)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [83]:
dtree.predict(test_x4)

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0], dtype=int64)

In [84]:
data4_score=dtree.score(test_x4,test_y4)

In [85]:
# 각 데이터셋 마다의 score 값
score={'data1':data1_score,'data2':data2_score,'data3':data3_score,'data4':data4_score}
print(score)

{'data1': 0.8379888268156425, 'data2': 0.8100558659217877, 'data3': 0.7821229050279329, 'data4': 0.7597765363128491}


In [86]:
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [87]:
rf=RandomForestClassifier()
xgb=XGBClassifier()

In [89]:
rf.fit(train_x4,train_y4)
xgb.fit(train_x4,train_y4)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, learning_rate=0.1,
       max_delta_step=0, max_depth=3, min_child_weight=1, missing=None,
       n_estimators=100, n_jobs=1, nthread=None,
       objective='binary:logistic', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=1, seed=None, silent=None,
       subsample=1, verbosity=1)

In [93]:
print('''rf : {}
xgb:{}
    '''.format(rf.score(test_x4,test_y4),xgb.score(test_x4,test_y4)))

rf : 0.7653631284916201
xgb:0.8100558659217877
    
