In [2]:
import numpy as np

In [3]:
def np_print(arr):
    txt='''
    shape : {}
    ndim: {}
    data: \n {}
    '''.format(arr.shape,arr.ndim,arr)
    print(txt)

# 배열 전환
## 1. 전치(Transpose)
- 배열의 행/열 인덱스가 바뀌는 변환
- 배열객체.T: 행/열 인덱스가 바뀐 새로운 배열을 반환하면 원본은 변경되지 않음

In [4]:
# 아이템 : 1 이상 13 미만의 정수값
# 구조 :  3*4
arr1=np.arange(1,13).reshape(3,4)
np_print(arr1)


    shape : (3, 4)
    ndim: 2
    data: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
    


In [5]:
arr1.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

# 배열 형태 변경
- arr.ravel(),np.ravel(arr)
    - 다차원 배열을 1차원 배열로 변환
    - np.ravel() : 1차원으로 변환되는 결과는 원본 배열에 반영되지 않음
    - arr.ravel() : 1차원으로 변환되는 결과는 원본 배열에 반영되지 않음
- arr.reshape(new_shape),np.reshape(arr,new_shape)
    - 원본 배열 객체의 구조(shape)를 변경
    - 변경하려는 구조의 전체 요소 개수와 원본 배열의 전체 요소 개수가 동일해야함
    - 변경하려는 구조의 튜플 중 하나의 원소는 -1로 대체할 수 있고 다른 하나의 원소를 기준으로 계산되어 사용됨
    - reshape() 메서드가 반환하는 배열의 요소가 변경되면 원본 배열에도 반영됨

In [6]:
# 다차원 배열을 1차원 배열로 변환
# 메서드이지만 원본구조가 바뀌지 않음
arr2=arr1.ravel()
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
# reshape으로 1d array로 못바꿈
arr1.reshape(1,12).shape

(1, 12)

In [12]:
arr2[0]=100
arr2

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12])

In [9]:
# 원본배열을 2열 기준으로 구조 변환 (나머지는 '-1'로 알아서 size 맞춰줌)
arr3=arr2.reshape(-1,2)

In [10]:
arr3

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [14]:
#변환 후 수정
#1행 값을 모두 1로 수정
arr3[0]=1
arr3

array([[ 1,  1],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [15]:
arr2

array([ 1,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# 요소 변경 추가 삭제
### 1. 요소 변경
- arr.resize((new_shape),np.resize(arr,(new_shape)
    - 배열 메서드를 사용하면 원본 변경, np 함수를 사용하면 새로운 배열 반환
    - 배열의 구조(reshape)를 변경하며 원본 배열의 요소 수와 동일하지 않아도 변경 가능
    - 변경되는 배열의 요소 수가 동일할 경우: reshape() 메서드와 동일한 결과
    - 변경된느 배열의 요소 수가 더 많을 경우
        - np.resize(arr,new_shape): 원본을 변경하지 않고, 모자란 부분을 기존 배열 값에서 복사해서 추가
        - arr.resize(new_shape): 원본을 변경하고, 모자란 부분을 0으로 채움
        - 공통적으로 new_shape은 튜플로 추가
    - 변경되는 배열의 요소 수가 더 작을 경우 : 마지막 남은 요소 삭제

In [11]:
# 아이템 : 1이상 10미만의 범위 에서 랜덤 정수
# 구조 3*5
arr1=np.random.randint(1,10,(3,5))
np_print(arr1)


    shape : (3, 5)
    ndim: 2
    data: 
 [[5 9 2 1 2]
 [7 5 9 3 1]
 [3 8 2 2 3]]
    


In [12]:
# 아이템 : 1이상 10미만의 범위 에서 랜덤 정수
# 구조 3*5
arr2= np.random.randint(1,10,(3,5))
np_print(arr2)


    shape : (3, 5)
    ndim: 2
    data: 
 [[9 5 5 6 6]
 [6 9 9 2 9]
 [1 2 8 6 5]]
    


In [13]:
# 변경되는 배열의 요소 수가 동일할 경우 : reshape()결과와 동일
# 변경할 구조 : 5*3
arr1.reshape(5,3)


array([[5, 9, 2],
       [1, 2, 7],
       [5, 9, 3],
       [1, 3, 8],
       [2, 2, 3]])

In [14]:
# resize: 원본 바뀜
arr1.resize((5,3))

In [15]:
arr1

array([[5, 9, 2],
       [1, 2, 7],
       [5, 9, 3],
       [1, 3, 8],
       [2, 2, 3]])

In [16]:
#변경되는 배열의 요소 수가 더 많을 경우 : 
# 변경할 구조: 4*5
arr2

array([[9, 5, 5, 6, 6],
       [6, 9, 9, 2, 9],
       [1, 2, 8, 6, 5]])

In [17]:
# np.resize()
np.resize(arr2,(4,5))

array([[9, 5, 5, 6, 6],
       [6, 9, 9, 2, 9],
       [1, 2, 8, 6, 5],
       [9, 5, 5, 6, 6]])

In [19]:
#arr.resize((4,5))
#error 발생 가능성 있음.. 왜..?? => refcheck=False 를 넣어줘라
arr2.resize((4,5),refcheck=False)

In [20]:
arr2

array([[9, 5, 5, 6, 6],
       [6, 9, 9, 2, 9],
       [1, 2, 8, 6, 5],
       [0, 0, 0, 0, 0]])

In [14]:
# 변경되는 배열의 요소 수가 더 작을 경우 : 남은 요소 삭제
#변경할 구조: 3*4
arr2

array([[6, 7, 7, 9, 7],
       [5, 9, 1, 4, 4],
       [1, 3, 7, 2, 5],
       [0, 0, 0, 0, 0]])

In [15]:
np.resize(arr2,(3,4))

array([[6, 7, 7, 9],
       [7, 5, 9, 1],
       [4, 4, 1, 3]])

In [24]:
arr2.resize((3,4),refcheck=False)

In [25]:
arr2

array([[6, 7, 7, 9],
       [7, 5, 9, 1],
       [4, 4, 1, 3]])

### 2. 요소 추가
- np.append(arr,values,axis=None)
    - arr 마지막에 values를 추가
    - axis 지정하지 않는 경우(기본값): 1차원 배열로 변형되어 결합
    - axis = 0 : 행 방향으로 결합 ( 단, 열의 개수가 동일해야함)
    - axis = 1 : 열 방향으로 결합 ( 단, 행의 개수가 동일해야함)
    - 원본 배열들에 반영되지 않음

In [24]:
# 아이템 : 1 이상 10 미만 차례대로 증가하는 정수
# 3*3
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
# 아이템 : 10 이상 19 미만 차례대로 증가하는 정수
# 3*3
b=np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [19]:
#2개의 배열 결합
# axis 지정하지 않는 경우: 1d array로 결합
# axis=None
np.append(a,b)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [22]:
# 2개의 배열 결합
# axis = 0 :행 단위로 결합
np.append(a,b,axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [23]:
# 2개의 배열 결합
# axis = 1 : 열단위 결합
np.append(a,b,axis=1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [27]:
# 아이템 : 30이상 45 미만 정수값
# 구조 : 3*5
c=np.arange(30,45).reshape(3,5)
c

array([[30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [28]:
# 열의 개수가 다른 배열과의 결합
# 행 단위로 결합 에러
np.append(a,c,axis=0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [32]:
# 위의 문제를 해결해보자
# 행 단위로 결합할 수 있는 구조로 변경
# 기준 : 열 개수
# 사용할 메서드 : reshape
np.append(a,c.reshape(-1,3),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [35]:
c1=c.copy()

In [36]:
# c의 구조 변경
# 4행 4열
c1.resize((4,4))
c1

array([[30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41],
       [42, 43, 44,  0]])

In [37]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [38]:
#열 단위 결합
c1.resize((3,4),refcheck=False)

In [39]:
c1

array([[30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41]])

In [40]:
np.append(b,c1,axis=1)

array([[10, 11, 12, 30, 31, 32, 33],
       [13, 14, 15, 34, 35, 36, 37],
       [16, 17, 18, 38, 39, 40, 41]])

- np.insert(arr,idx,values,axis=None)
    - 지정한 인덱스(idx)에 value를 추가
    - axis 지정하지 않는 경우(기본값): 1차원 배열의 변형되고 해당 인덱스에 추가
    - axis = 0 : 행 방향으로 n번째 행에 추가
    - axis = 1 : 열 방향으로 n번쨰 열에 추가
    - 원본 배열엔 반영되지 않음

In [28]:
# 아이템: 1이상 10 미만
# 구조: 3*3
x1=np.arange(1,10).reshape(3,3)
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
# axis 지정하지 않는 경우
# 원본객체가 1d array 가 됐을 때의 인덱스 번호(1)에 100을 추가
np.insert(x1,1,100)

array([  1, 100,   2,   3,   4,   5,   6,   7,   8,   9])

In [30]:
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
# axis =0 행방향 => n번 인덱스 행에 추가
# value가 하나의 값이면 모든 행 요소에 추가
np.insert(x1,1,100,axis=0)

array([[  1,   2,   3],
       [100, 100, 100],
       [  4,   5,   6],
       [  7,   8,   9]])

In [32]:
np.insert(x1,1,100,axis=1)

array([[  1, 100,   2,   3],
       [  4, 100,   5,   6],
       [  7, 100,   8,   9]])

In [33]:
# 요소마다 다른 값으로 행/열을 추가
# 동일한 요소 개수(행/열의 요소 개수)를 가지는 리스트로 value 전달
np.insert(x1,1,[10,20,30],axis=0)

array([[ 1,  2,  3],
       [10, 20, 30],
       [ 4,  5,  6],
       [ 7,  8,  9]])

## 요소 삭제
- np.delete(arr,idx,axis=None)
    - 지정한 인덱스에 해당하는 요소를 삭제
    - axis 지정하지 않는 경우(기본값): 1차원 배열로 변형되어 해당 인덱스에 해당하는 요소를 삭제
    - axis = 0: 행 방향으로 n번째 행을 삭제
    - axis = 1: 열 방향으로 n번째 열을 삭제
    - 원본배열엔 반영되지 않음

In [34]:
# axis 지정 안함: 1d 배열로 변환 후 지정한 인덱스의 요소를 삭제
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
np.delete(x1,4)  # 4번 인덱스 삭제

array([1, 2, 3, 4, 6, 7, 8, 9])

In [53]:
# 원본 배열 변화 안함
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
# axis = 0 : 행 삭제
np.delete(x1,0,axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

In [55]:
np.delete(x1,0,axis=1)

array([[2, 3],
       [5, 6],
       [8, 9]])

### 배열 결합
- np.concatenate((arr1),arr2,...),axis=0)
    - axis=0(기본값): 행 방향으로 두 배열 결합(단, 열의 개수가 동일)
    - axis=1: 열 방향으로 두 배열 결합(단,행의 개수가 동일)
    - 원본 배열들은 변경되지 않음

In [36]:
# 4개의 배열 생성
# 1~7=2*3 , 7~13=2*3, 13~23=2*5 23~38=5*2
a=np.arange(1,7).reshape(2,3)
b=np.arange(7,13).reshape(2,3)
c=np.arange(13,23).reshape(2,5)
d=np.arange(23,38).reshape(5,3)

In [59]:
# 행 방향으로 a,b 배열 결합
np.append(a,b,axis=0)   #둘이 결과값 같음
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [60]:
#열방향
np.concatenate((a,b),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [63]:
# 행방향 결합조건: 열 개수 동일
np.concatenate((a,c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [65]:
# 열방향 결합조건: 행 개수 동일
np.resize(d,(3,4))

array([[23, 24, 25, 26],
       [27, 28, 29, 30],
       [31, 32, 33, 34]])

In [67]:
np.concatenate((a,np.resize(d,(2,4))),axis=1)

array([[ 1,  2,  3, 23, 24, 25, 26],
       [ 4,  5,  6, 27, 28, 29, 30]])

- vstack() 메서드
    - np.vstack((arr1,arr2...))
    - 튜플로 전달받은 여러 개의 배열을 행 방향(수직 방향)으로 결합
    - 열 개수가 동일해야 함
    - np.concatenate((arr1,arr2...),axis=0)과 동일한 결과
    - 원본 배열들은 변경되지 않음

In [68]:
#2행3열
a

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
np.vstack((a,d))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34],
       [35, 36, 37]])

In [72]:
# 4개 결합
np.vstack((a,d,a,d))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34],
       [35, 36, 37],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34],
       [35, 36, 37]])

- np.hstack((arr1,arr2...))
    - np.hstack((arr1,arr2...))
    - 튜플로 전달받은 여러 개의 배열을 행 방향(수평 방향)으로 결합
    - 행 개수가 동일해야 함
    - np.concatenate((arr1,arr2...),axis=1)과 동일한 결과
    - 원본 배열들은 변경되지 않음


In [74]:
np.hstack((b,c,b,c))

array([[ 7,  8,  9, 13, 14, 15, 16, 17,  7,  8,  9, 13, 14, 15, 16, 17],
       [10, 11, 12, 18, 19, 20, 21, 22, 10, 11, 12, 18, 19, 20, 21, 22]])

- stack()
    - np.stack((arr1,arr2...))
    - 튜플로 전달받은 여러 개의 배열을 3차원으로 결합
    - 행, 열의 구조가 동일해야 함

In [78]:
# 2개의 층을 가진 3차원 배열로 변환됨
np.stack((a,b))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [77]:
np.stack((a,b)).shape

(2, 2, 3)

5) 배열 분리
- np.vsplit(arr,indices_or_sections)
    - 배열을 행 방향으로 분리하여 각 배열을 리스트로 묶어서 반환
    - 분리할 그룹 개수를 지정 : 균등하게 분리
    - 분리할 기준 인덱스를 리스트로 전달: 균등하지 않게 분리
    - 원본 배열의 구조와 비료하여 아이템 개수가 변경
    - 원본 배열은 변경되지 않음

In [4]:
# 아이템 : 1이상 37 미만 범위
# 구조: 6*6
a=np.arange(1,37).reshape(6,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [7]:
# 결과 배열의 개수를 기준으로 나누기
# 기준 : 행 방향으로 3개로 나누기
# 반환값: 부분 배열을 저장하고 있는 리스트
a_split=np.vsplit(a,3)
type(a_split)

list

In [8]:
a_split[0]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [9]:
# vsplist 변환객체의 하위 아이템은 다시 배열
a_split[0].shape

(2, 6)

In [10]:
# 원본 배열은 변경되지 않음
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [11]:
# 간격이 균등하지 않은 경우
np.vsplit(a,4)    # 에러가 남

ValueError: array split does not result in an equal division

In [16]:
# 균등하지 않은 범위에서 행을 기준으로 배열 나누기
#0   
#1~2
#3
#4~5
#section => [1,3,4,6]
for arr in np.vsplit(a,[1,3,4]):
    print(arr)
    print()

[[1 2 3 4 5 6]]

[[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]

[[19 20 21 22 23 24]]

[[25 26 27 28 29 30]
 [31 32 33 34 35 36]]



- np.hsplit(arr,indices_or_sections)
    - 배열을 열 방향으로 분리하여 각 배열을 리스트로 묶어서 반환
    - 분리할 그룹 개수를 지정 : 균등하게 분리
    - 분리할 기준 인덱스를 리스트로 전달: 균등하지 않게 분리
    - 원본 배열의 구조와 비료하여 아이템 개수가 변경
    - 원본 배열은 변경되지 않음

In [17]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [18]:
# 열 방향으로 6개로 분리
np.hsplit(a,6)

[array([[ 1],
        [ 7],
        [13],
        [19],
        [25],
        [31]]), array([[ 2],
        [ 8],
        [14],
        [20],
        [26],
        [32]]), array([[ 3],
        [ 9],
        [15],
        [21],
        [27],
        [33]]), array([[ 4],
        [10],
        [16],
        [22],
        [28],
        [34]]), array([[ 5],
        [11],
        [17],
        [23],
        [29],
        [35]]), array([[ 6],
        [12],
        [18],
        [24],
        [30],
        [36]])]

In [19]:
# 균등하지 않은 기준으로 분리
# section=[2,5] => 1번 인덱스, 4번 인덱스 => 3개
np.hsplit(a,[2,5])

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20],
        [25, 26],
        [31, 32]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23],
        [27, 28, 29],
        [33, 34, 35]]), array([[ 6],
        [12],
        [18],
        [24],
        [30],
        [36]])]

- np.split(arr,indicates_or_section, axis)


In [21]:
# 균등하지 않은 간격으로 행 기준으로 분리
# np.split(a,section,axis=0) = np.vsplit(a,section)
np.split(a,[2,5],axis=0)

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]]), array([[31, 32, 33, 34, 35, 36]])]

In [22]:
np.split(a,[2,5])

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]]), array([[31, 32, 33, 34, 35, 36]])]

In [23]:
# 균등한 간격으로 열 기준으로 분리
np.split(a,3,axis=0)

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]), array([[25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]])]