In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
wine=pd.read_csv('winequality-white.csv',sep=';')

In [3]:
wine.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [4]:
# 데이터셋 준비
# 분류모델
# GridSearchCV
# 분류정확도
# ConfusionMatrix
# +Classification

In [5]:
# 종속변수 quality
# 독립변수 나머지

In [6]:
wine.shape

(4898, 12)

In [7]:
wine_x=wine.iloc[:,:-1]
wine_y=wine['quality'].copy()

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
train_x,test_x,train_y,test_y=train_test_split(wine_x,wine_y,test_size=.2)

In [10]:
from sklearn.tree import DecisionTreeClassifier

In [11]:
dt=DecisionTreeClassifier()

In [12]:
dt.fit(train_x,train_y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [13]:
dt.score(test_x,test_y)

0.5979591836734693

In [14]:
# 랜덤 포레스트
from sklearn.ensemble import RandomForestClassifier

In [15]:
rf=RandomForestClassifier()
rf.fit(train_x,train_y)

C:\Users\winst\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [16]:
rf.score(test_x,test_y)

0.6479591836734694

## 파라미터 최적화

In [17]:
param_grid={'max_features':[None,'sqrt'],
           'criterion':['gini','entropy'],
           'max_depth':[3,5,7,9],
           'min_samples_leaf':[0.001,0.01,0.1,0.5]}

In [18]:
from sklearn.model_selection import GridSearchCV

In [19]:
dt2=DecisionTreeClassifier()

In [20]:
# GridSearch 수행 = cv 기본값(3)
grid_search=GridSearchCV(estimator=dt2,param_grid=param_grid)
grid_search.fit(train_x,train_y)

C:\Users\winst\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'max_features': [None, 'sqrt'], 'criterion': ['gini', 'entropy'], 'max_depth': [3, 5, 7, 9], 'min_samples_leaf': [0.001, 0.01, 0.1, 0.5]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [21]:
dt3=DecisionTreeClassifier()

In [22]:
# GridSearch 수행 = cv (5)
grid2=GridSearchCV(dt3,param_grid,cv=5)

In [23]:
grid2.fit(train_x,train_y)

C:\Users\winst\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 3 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'max_features': [None, 'sqrt'], 'criterion': ['gini', 'entropy'], 'max_depth': [3, 5, 7, 9], 'min_samples_leaf': [0.001, 0.01, 0.1, 0.5]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [24]:
grid_search.best_params_

{'criterion': 'gini',
 'max_depth': 9,
 'max_features': None,
 'min_samples_leaf': 0.001}

In [25]:
grid_search.best_score_

0.5400714650331802

In [27]:
grid2.best_params_

{'criterion': 'gini',
 'max_depth': 9,
 'max_features': None,
 'min_samples_leaf': 0.001}

In [28]:
grid2.best_score_

0.5525778458397141

In [29]:
grid_search.score(test_x,test_y)

0.539795918367347

In [30]:
grid2.score(test_x,test_y)

0.5418367346938775

In [31]:
# Cross-validation : 교차검증
from sklearn.model_selection import cross_validate

In [32]:
dt5=DecisionTreeClassifier()

In [33]:
result=cross_validate(dt5,wine_x,wine_y,cv=5,return_train_score=True)

In [34]:
result['test_score'].mean()

0.41510355831794454

In [35]:
result['train_score']

array([1., 1., 1., 1., 1.])

### 성능 평가

In [36]:
from sklearn.metrics import confusion_matrix

In [37]:
grid2=GridSearchCV(dt3,param_grid,cv=5)

In [38]:
grid2.fit(train_x,train_y)

C:\Users\winst\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 3 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'max_features': [None, 'sqrt'], 'criterion': ['gini', 'entropy'], 'max_depth': [3, 5, 7, 9], 'min_samples_leaf': [0.001, 0.01, 0.1, 0.5]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [39]:
# confusion_matrix 결과값
pred_y=grid2.predict(test_x)

In [40]:
test_y.unique()

array([6, 7, 5, 4, 3, 8, 9], dtype=int64)

In [41]:
label=range(3,10)
confusion_matrix(test_y,pred_y)


array([[  0,   0,   3,   1,   0,   0,   0],
       [  0,   3,  23,   9,   2,   0,   0],
       [  0,   6, 189,  81,  18,   1,   0],
       [  1,   2, 121, 268,  46,   4,   0],
       [  0,   2,  10,  97,  64,   1,   0],
       [  0,   0,   2,  11,   8,   5,   0],
       [  0,   0,   0,   1,   0,   1,   0]], dtype=int64)

In [42]:
test_y.value_counts()

6    442
5    295
7    174
4     37
8     26
3      4
9      2
Name: quality, dtype: int64

In [43]:
# pd.cross-table(예측값,실제값)
pd.crosstab(pred_y,test_y)

quality  3   4    5    6   7   8  9
row_0                              
3        0   0    0    1   0   0  0
4        0   3    6    2   2   0  0
5        3  23  189  121  10   2  0
6        1   9   81  268  97  11  1
7        0   2   18   46  64   8  0
8        0   0    1    4   1   5  1